apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1-10g-002
spec:
  capacity:
    storage: 10G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    fsType: ext4
    path: /dev/mapper/k8s--vg-PV10G002
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sw-k8s-stgn01
