# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-ingress/service.yaml
  - nginx-ingress/deployment.yaml

configMapGenerator:
- name: nginx-config
  files:
  - nginx-ingress/nginx.conf
